name: Deploy on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build and push Docker image
        run: |
          docker build -t  ${{ secrets.DOCKER_USERNAME }}/devops:pr-${{ github.event.number }} .
          docker push  ${{ secrets.DOCKER_USERNAME }}/devops:pr-${{ github.event.number }}