name: docker-build-post

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up
        uses: docker/setup-buildx-action@v2

      - name: Log in
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build and push image
        run: |
          docker build -t  devops:ver-${{ github.event.number }} .
          docker push  devops:ver-${{ github.event.number }}